import os
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

REPORTS_DIR = "data/reports"


def generate_pdf(session_id: str, data: dict) -> str:
    os.makedirs(REPORTS_DIR, exist_ok=True)
    pdf_path = f"{REPORTS_DIR}/{session_id}.pdf"

    doc = SimpleDocTemplate(pdf_path, pagesize=A4, topMargin=2 * cm, bottomMargin=2 * cm)
    styles = getSampleStyleSheet()
    story = []

    title_style = ParagraphStyle("Title", parent=styles["Title"], textColor=colors.HexColor("#1e40af"))
    h2_style = ParagraphStyle("H2", parent=styles["Heading2"], textColor=colors.HexColor("#1e40af"))
    body = styles["BodyText"]

    # ── Header ──────────────────────────────────────────────────────────────
    story.append(Paragraph("🧬 Drug Discovery Research Report", title_style))
    story.append(Paragraph(f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", body))
    story.append(Paragraph(f"Session ID: {session_id}", body))
    story.append(HRFlowable(width="100%", color=colors.HexColor("#1e40af")))
    story.append(Spacer(1, 0.4 * cm))

    # ── Protein Overview ─────────────────────────────────────────────────────
    parsed = data.get("parsed", {})
    story.append(Paragraph("1. Protein Overview", h2_style))
    overview_data = [
        ["Property", "Value"],
        ["Filename", data.get("filename", "—")],
        ["Name", parsed.get("name", "—")],
        ["Organism", parsed.get("organism", "—")],
        ["Resolution (Å)", str(parsed.get("resolution") or "—")],
        ["Total Chains", str(len(parsed.get("chains", [])))],
        ["Total Residues", str(parsed.get("total_residues", "—"))],
        ["Total Atoms", str(parsed.get("total_atoms", "—"))],
    ]
    story.append(_make_table(overview_data))
    story.append(Spacer(1, 0.4 * cm))

    # ── Chains ───────────────────────────────────────────────────────────────
    if parsed.get("chains"):
        story.append(Paragraph("2. Chain Summary", h2_style))
        chain_data = [["Chain", "Residues", "HETATMs", "Atoms", "Sequence (first 40)"]]
        for c in parsed["chains"]:
            chain_data.append([
                c["chain_id"],
                str(c["residue_count"]),
                str(c["hetatm_count"]),
                str(c["atom_count"]),
                c.get("sequence", "")[:40] + ("…" if len(c.get("sequence", "")) > 40 else ""),
            ])
        story.append(_make_table(chain_data))
        story.append(Spacer(1, 0.4 * cm))

    # ── Binding Pockets ──────────────────────────────────────────────────────
    pockets = data.get("pockets", [])
    story.append(Paragraph("3. Binding Pocket Detection", h2_style))
    if pockets:
        pocket_data = [["Pocket #", "Druggability Score", "Volume (Å³)", "Note"]]
        for p in pockets:
            pocket_data.append([
                str(p.get("pocket_id", "—")),
                f"{p.get('druggability_score', 0):.2f}",
                f"{p.get('volume', 0):.1f}",
                p.get("note", "fpocket"),
            ])
        story.append(_make_table(pocket_data))
    else:
        story.append(Paragraph("No pockets detected.", body))
    story.append(Spacer(1, 0.4 * cm))

    # ── Drug Candidates ──────────────────────────────────────────────────────
    drugs = data.get("drugs", [])
    story.append(Paragraph("4. Drug Candidates", h2_style))
    if drugs:
        for drug in drugs:
            story.append(Paragraph(f"<b>{drug.get('name', '—')}</b>", body))
            story.append(Paragraph(f"CID: {drug.get('cid', '—')} | MW: {drug.get('molecular_weight', '—')} | Formula: {drug.get('formula', '—')}", body))
            if drug.get("reasoning"):
                story.append(Paragraph(f"AI Reasoning: {drug['reasoning']}", body))
            story.append(Spacer(1, 0.2 * cm))
    else:
        story.append(Paragraph("No drug suggestions generated.", body))

    # Footer
    story.append(Spacer(1, 0.4 * cm))
    story.append(Paragraph("5. Methods", h2_style))
    story.append(
        Paragraph(
            "Pockets were generated using fpocket (or imported fpocket-format results). "
            "Drug candidates were retrieved from PubChem and reasoned with Gemini.",
            body,
        )
    )

    story.append(Spacer(1, 0.4 * cm))
    story.append(HRFlowable(width="100%", color=colors.grey))
    story.append(Paragraph("Generated by Agentic Drug Discovery Copilot", body))

    doc.build(story)
    return pdf_path


def _make_table(data: list[list]) -> Table:
    t = Table(data, hAlign="LEFT")
    t.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1e40af")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#eff6ff")]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#bfdbfe")),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("PADDING", (0, 0), (-1, -1), 5),
        ])
    )
    return t
